-- Oracle Database 23ai+ script for RAG service
-- Run as SYS or a DBA user first, then connect as RAG_APP to create objects.

CREATE USER RAG_APP IDENTIFIED BY "RagPassword123"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE INDEX TO RAG_APP;

-- connect as RAG_APP

CREATE TABLE rag_chunks (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    document_id VARCHAR2(64) NOT NULL,
    file_name VARCHAR2(512) NOT NULL,
    content_type VARCHAR2(255),
    chunk_number NUMBER NOT NULL,
    chunk_text CLOB NOT NULL,
    embedding VECTOR(384, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX rag_chunks_doc_idx ON rag_chunks (document_id);

-- IVF vector index for ANN similarity search
CREATE VECTOR INDEX rag_chunks_embedding_vidx
ON rag_chunks (embedding)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95;
